<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    '8d7decb96779896b59d972a4ec7a127d' => $vendorDir . '/symfony/polyfill-php80/bootstrap.php',
);
