<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit1155dada1f28af1fa0fb1bc9b0e382d4
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('WPWS\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \WPWS\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        spl_autoload_register(array('ComposerAutoloaderInit1155dada1f28af1fa0fb1bc9b0e382d4', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \WPWS\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit1155dada1f28af1fa0fb1bc9b0e382d4', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\WPWS\Vendor\Composer\Autoload\ComposerStaticInit1155dada1f28af1fa0fb1bc9b0e382d4::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        $filesToLoad = \WPWS\Vendor\Composer\Autoload\ComposerStaticInit1155dada1f28af1fa0fb1bc9b0e382d4::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
